version: '3.5'

services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile  
    expose:
      - "3000"

  # db:
  #   image: postgres
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=discord-bot
  #   ports:
  #     - '127.0.0.1:15432:5432'
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #     - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:ro

# volumes:
#   postgres-data: