name: Build and publish docker image
on:
  workflow_dispatch: 

env:
  IMAGE: arelstone/lst-discord-bot
  TAG: latest


permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  # build:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: |
  #         docker build -t ${{ env.IMAGE }}:${{ env.TAG }} .
  #         docker push ${{ env.IMAGE }}
  
  connect:
    runs-on: ubuntu-latest
    # needs:
    #   - build
    steps:
      - uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.PATTY_HOST }}
          username: ${{ secrets.PATTY_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PATTY_PORT }}
          script: whoami