name: pull-request
on:
  pull_request:
    types: [opened, synchronize, edited]
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ensure that title uses gitmoji
        uses: paralenz/actions/gitmoji@v2.1.7
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Linting
        run: yarn lint
      - name: Build
        run: yarn build